/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplojframeenviodeobjetos;

import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author viti
 */
public class JframePrincipal extends javax.swing.JFrame {

    public static Datos datos = new Datos();
    
    /**
     * Creates new form JframePrincipal
     */
    public JframePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelModificable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 2000, 2000));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBounds(new java.awt.Rectangle(0, 0, 2000, 2000));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Datos que vamos a imprimir");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 10, 250, 40);

        jLabelModificable.setText("jLabel2");
        jPanel1.add(jLabelModificable);
        jLabelModificable.setBounds(20, 60, 300, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 800, 390);

        jButton1.setText("ModificaDatos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 540, 200, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("ejemplojframeenviodeobjetos.JframePrincipal.jButton1ActionPerformed()");
        datos.estudiantes[1].setNombre("LE CAMBIE EL NOMBRE");
        jTextArea1.setText(datos.toString());
        System.out.println(datos.toString());
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JframePrincipal frame = new JframePrincipal();
                 
                  // Configuración esencial para maximización correcta
                frame.setLayout(new BorderLayout());  // 1. Layout principal del JFrame
                frame.jPanel1.setLayout(new BorderLayout()); // 2. Layout del panel principal
            
               // 3. Asegurar que el panel ocupe todo el espacio
                frame.add(frame.jPanel1, BorderLayout.CENTER);
            
                // 4. Configuración de componentes
                frame.jTextArea1.setLineWrap(true);
                frame.jTextArea1.setWrapStyleWord(true);
            
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH); // Aquí se maximiza
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                frame.jPanel1.setLayout(new BorderLayout());
                
                
                frame.jLabelModificable.setText(datos.universidad.getNombre());
                frame.jTextArea1.setText(datos.toString());
                
                
                frame.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelModificable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
